<?php

namespace app\controller\index;

use app\database\dao\UserDao;
use nova\framework\request\Controller;
use nova\framework\request\Response;

class Database extends Controller
{

    public function init(): ?Response
    {


        return parent::init(); // TODO: Change the autogenerated stub
    }


    public function register():Response
    {
        $user = new \app\database\model\UserModel();
        $user->user = "admin";
        $user->password = "admin";
        UserDao::getInstance()->add($user);
        $list = UserDao::getInstance()->list();
        return Response::asJson($list);
    }

}